<a href="https://colab.research.google.com/github/leighd2008/TF-class-colab-notebooks/blob/main/00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [ ]:
import tensorflow as tf


In [ ]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
scalar = tf.constant(42)
vector = tf.constant([2, 21])
matrix = tf.constant([[1, 2],
                [3, 4]])
tensor = tf.constant([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a, b, C, D

(<tf.Tensor: shape=(), dtype=int32, numpy=42>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 21], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]], dtype=int32)>)

In [ ]:
# Find the shape, rank and size of the tensors you created in 1.
print(f'The shape of the tensor: {tensor.shape}')
print(f'The rank of the tensor: {tf.rank(tensor)}')
print(f'The size of the tensor: {tf.size(tensor)}')

The shape of the tensor: (2, 3, 3)
The rank of the tensor: 3
The size of the tensor: 18


In [ ]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300].

tf.random.set_seed(42)

tensor_1 = tf.random.uniform(shape=(5, 300))
tensor_2 = tf.random.uniform(shape=(5, 300))

tensor_1, tensor_1.shape, tensor_2, tensor_2.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

In [ ]:
# Multiply the two tensors you created in 3 using matrix multiplication.
tensorMM = tf.matmul(tensor_1, tf.transpose(tensor_2))
tensorMM


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33344 , 73.40498 , 77.15962 , 73.98368 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.085266, 69.06406 , 74.307755, 72.27616 , 76.05668 ],
       [85.056885, 74.266266, 78.00687 , 74.88678 , 83.13418 ]],
      dtype=float32)>

In [ ]:
# Multiply the two tensors you created in 3 using dot product.
tensorDP = tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)
tensorDP


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33344 , 73.40498 , 77.15962 , 73.98368 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.085266, 69.06406 , 74.307755, 72.27616 , 76.05668 ],
       [85.056885, 74.266266, 78.00687 , 74.88678 , 83.13418 ]],
      dtype=float32)>

In [ ]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor_3 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

In [ ]:
# Find the min and max values of the tensor you created in 6 along the first axis.
min = tf.math.reduce_min(tensor_3)
max = tf.math.reduce_max(tensor_3)
min, max

(<tf.Tensor: shape=(), dtype=float32, numpy=2.3841858e-07>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999918>)

In [ ]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor_4 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor_4_sq = tf.squeeze(tensor_4)
tensor_4, tensor_4_sq

(<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
 array([[[[8.0315602e-01, 4.9777734e-01, 3.7054038e-01],
          [9.1186738e-01, 6.3764203e-01, 1.8209696e-01],
          [6.3791955e-01, 2.7701473e-01, 4.2271137e-02],
          ...,
          [1.0830712e-01, 4.5979273e-01, 2.5716281e-01],
          [8.7138689e-01, 1.8434000e-01, 4.4757760e-01],
          [7.4110627e-02, 9.0852141e-01, 5.3693414e-01]],
 
         [[5.5596435e-01, 6.8776274e-01, 7.6051474e-02],
          [1.6737962e-01, 7.1785092e-01, 2.7642274e-01],
          [2.6995218e-01, 3.2203627e-01, 8.8224900e-01],
          ...,
          [4.8168826e-01, 5.0150025e-01, 8.6756039e-01],
          [4.1261053e-01, 1.2770486e-01, 5.8186901e-01],
          [2.5495613e-01, 3.9036548e-01, 9.8529553e-01]],
 
         [[8.0935180e-01, 1.9740558e-01, 3.5899937e-01],
          [1.1216915e-01, 9.1016293e-04, 3.6382091e-01],
          [5.1202202e-01, 3.9188230e-01, 8.8335538e-01],
          ...,
          [2.0133841e-01, 9.1663551

In [ ]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor_5 = tf.constant([1, 2, 8, 6, 5, 3, 7, 9, 4, 0])
max_arg = tf.argmax(tensor_5)
max_val = tensor_5[max_arg]
tensor_5, max_arg, max_val

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 2, 8, 6, 5, 3, 7, 9, 4, 0], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=7>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [ ]:
# One-hot encode the tensor you created in 9.
tf.one_hot(tf.cast(tensor_5 , dtype=tf.int32) , depth = 10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>